"""
Utility to read EnergyPlus eplustbl.csv output files for specific data.

This module provides functions to read key data from the eplustbl.csv output file 
generated by EnergyPlus simulations. Currently it extracts:

1. Glazing area data from "Area of Multiplied Openings [m2]" column
2. Glazing U-value data from "Glass U-Factor [W/m2-K]" column

These values are used in area reports to provide more accurate glazing information
based on the simulation results rather than the IDF input file values.
"""
import csv
import os
from typing import Dict, Any, Optional

def safe_float(value: Any, default: float = 0.0) -> float:
    """
    Safely convert a value to float, returning default if conversion fails.
    """
    if value is None:
        return default
    try:
        return float(value)
    except (ValueError, TypeError):
        return default

def _find_csv_path(csv_path: Optional[str]) -> Optional[str]:
    if csv_path and os.path.exists(csv_path):
        return csv_path
    default_path = os.path.join("simulation_output", "eplustbl.csv")
    if os.path.exists(default_path):
        return default_path
    return None

def _parse_exterior_fenestration_table(reader) -> Dict[str, Dict[str, Any]]:
    header_map = {
        "construction": 1,
        "area of multiplied openings [m2]": 6,
        "glass u-factor [w/m2-k]": 7,
        "glass shgc": 8,
        "glass visible transmittance": 9
    }
    col_indices = {}
    result = {}
    in_target_table = False
    headers_found = False
    for row in reader:
        if not row or not any(field.strip() for field in row):
            continue
        if not in_target_table and row[0].strip().lower() == "exterior fenestration":
            in_target_table = True
            headers_found = False
            col_indices = {}
            continue
        if in_target_table:
            if not headers_found:
                current_headers_norm = [h.strip().lower() for h in row]
                if "construction" in current_headers_norm and "glass u-factor [w/m2-k]" in current_headers_norm:
                    for key in header_map:
                        if key in current_headers_norm:
                            col_indices[key] = current_headers_norm.index(key)
                        else:
                            raise ValueError(f"Missing required header: '{key}'")
                    if len(col_indices) != len(header_map):
                        missing = set(header_map.keys()) - set(col_indices.keys())
                        raise ValueError(f"Missing required headers: {missing}")
                    headers_found = True
                continue
            else:
                is_total_row = row[0].strip().lower().endswith("total or average")
                is_blank_data_row = not row[0].strip() and (len(row) < 2 or not row[1].strip())
                if is_total_row or is_blank_data_row:
                    break
                max_index = max(col_indices.values()) if col_indices else -1
                if max_index == -1:
                    break
                if len(row) > max_index:
                    construction_name = row[col_indices["construction"]].strip()
                    area = safe_float(row[col_indices["area of multiplied openings [m2]"]])
                    u_value = safe_float(row[col_indices["glass u-factor [w/m2-k]"]])
                    if construction_name:
                        result[construction_name] = {
                            'Area': area,
                            'U-Value': u_value,
                        }
    return result

def read_glazing_data_from_csv(csv_path: Optional[str] = None) -> Dict[str, Dict[str, Any]]:
    """
    Read glazing data from the eplustbl.csv file.
    Returns a dictionary mapping construction names to their properties.
    Raises FileNotFoundError or ValueError for missing files or headers.
    """
    result = {}
    resolved_path = _find_csv_path(csv_path)
    if not resolved_path:
        raise FileNotFoundError("eplustbl.csv not found in provided path or simulation_output directory.")
    try:
        with open(resolved_path, 'r', encoding='utf-8', errors='ignore') as csvfile:
            reader = csv.reader(csvfile)
            result = _parse_exterior_fenestration_table(reader)
    except FileNotFoundError:
        raise FileNotFoundError(f"CSV file not found: {resolved_path}")
    except ValueError as e:
        raise ValueError(f"CSV header error: {e}")
    except Exception as e:
        raise RuntimeError(f"Error reading or parsing CSV: {e}")
    return result
